name: Docker deploy

#on: workflow_call
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        env:
            docker_login: ${{ secrets.DOCKER_LOGIN}} # pourquoi il faut passer par ENV et non pas pouvour utiliser secrets directement?
            docker_pta: ${{ secrets.DOCKER_PTA }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.docker_login}}
          password: ${{ env.docker_pta }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: bilgacosmin/pipeline