name: Docker deploy

#on: workflow_call
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_LOGIN}}
          password: ${{ secrets.DOCKER_PTA }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: bilgacosmin/pipeline:1.0