name: Docker deploy

on: workflow_call
#on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v3
            - run:
                echo Nevastuik91 | docker login -u bilgacosmin --password-stdin
            - run: \
                docker build . --tag bilgacosmin/pipeline \
                docker push bilgacosmin/pipeline