name: Docker deploy

on: workflow_call

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v3
            - run:
                echo ${{secrets.DOCKER_PASSWD}} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
            - run: \
                docker build . --tag bilgacosmin/pipeline \
                docker push bilgacosmin/pipeline